### ISSUE TITLE
What version of sikuli did you integrate your framework with ?

### ISSUE THREAD

**Issue by mmoselhy** [smysnk/sikuli-framework#3]
Hello,

I'm trying to use the framework on Windows/Linux

first, I tried to run the calculator example but it gives me the below error
"*TRACE:1432030308240* Changing screenshot logging level
*INFO:1432030308255* [<class 'launcher.Launcher'>]() is attempting to run [Calculator] wd=C:\Users\
moselhy\Desktop\Sikuli\sikuli-framework-master
*TRACE:1432030308255* [Calculator:Application]() created
*INFO:1432030308255* [<class 'launcher.Launcher'>]() created [Calculator] from [calc.exe] [WINDOWS
in7 x86]
Traceback (most recent call last):
  File "examples\calculator\add.py", line 48, in <module>
    calculator = Launcher.run('Calculator')
  File "C:\Users\mmoselhy\Desktop\Sikuli\sikuli-framework-master\src\launcher.py", line 65, in run
    result = subprocess.Popen(binary, shell=True, cwd=app.getWorkingDir(os, osVersion, arch))
  File "C:\Users\mmoselhy\Desktop\Sikuli\sikuli-framework-master\java\sikuli-script.jar\Lib\subproc
ss.py", line 751, in __init__
  File "C:\Users\mmoselhy\Desktop\Sikuli\sikuli-framework-master\java\sikuli-script.jar\Lib\subproc
ss.py", line 1236, in _execute_child
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'"

the launcher isn't working, do u have any idea why ? 
also, I want to integrate with the latest sikuli jar, I found that you use sikuli-script.jar
and this is replaced by sikuli-java.jar in the latest release 1.0.1 . but it misses many dependencies.

I'm willing to support your project and push some work as I find it very useful.
but I'm still need some info as I'm somehow confused :)
i

**Comment by RaiMan** [comment]
Hi this is RaiMan from SikuliX.

I am also willing to support the integration of version 1.1.0 (sikulixapi.jar).

... and there is another interesting RFW approach (already working with 1.1.0)
https://github.com/Tset-Noitamotua/Sikuli-and-Robot-Framework-Integration

So let us know, how we can help.

**Comment by mmoselhy** [comment]
Hi RaiMan,
well, I have a couple of simple questions.

as I understand, this framework has been done using sikuli-script.jar from older release ?
and it's replacement in v1.0.1 is sikuli-java.jar and the latest replacement is sikulxapi.jar right ?


I started working to move it to 1.0.1 but since 1.1.0 version will be released soon, so I'll switch my effort to 1.1.0 night builds

also, Thanks for referring to the other framework integration, it will help a lot.

**Comment by RaiMan** [comment]
@mmoselhy 
yes with 1.1.0+ it is sikulixapi.jar.

… and I recommend to use it for these purposes.

Come back with any question.

**Comment by smysnk** [comment]
This appears to be a problem with launching the calculator executable.

I would inspect what arguments are being passed into
`src\launcher.py:65: result = subprocess.Popen(binary, shell=True, cwd=app.getWorkingDir(os, osVersion, arch))`

You may want to try specifying the exact path to calc.exe @ https://github.com/smysnk/sikuli-framework/blob/master/examples/calculator/maps/calculator.py#L67
